# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-20 14:47
# Modified to skip during initial migration

from django.db import migrations

def insert_def(apps, schema_editor):
    # Skip during migration - will be handled by later migrations
    pass

def remove_def(apps, schema_editor):
    pass
        
class Migration(migrations.Migration):
    dependencies = [
        ('gvsigol_services', '0038_auto_20201021_1305'),
    ]

    operations = [
        migrations.RunPython(insert_def, reverse_code=remove_def),
    ]
